npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".mp4"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".mov"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".mpg"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".mpeg"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".wmv"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".avi"
npm run add-s3-handler --s3_bucket="pulsedin-prod-storage" --s3_prefix="storage/" --s3_suffix=".webm"
